#!/bin/bash
# BitWarden Provider Implementation
# Implements the vault provider interface for BitWarden CLI (bw)

provider_name() {
    echo "bitwarden"
}

provider_check_installed() {
    command -v bw &> /dev/null
}

provider_install_instructions() {
    echo "BitWarden CLI installation:"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "  brew install bitwarden-cli"
    elif [[ -f /etc/debian_version ]]; then
        echo "  sudo snap install bw"
        echo "  # or: npm install -g @bitwarden/cli"
    else
        echo "  npm install -g @bitwarden/cli"
    fi
}

provider_login() {
    local status
    status=$(bw status 2>/dev/null | jq -r '.status' 2>/dev/null || echo "unauthenticated")

    if [[ "$status" == "unauthenticated" ]]; then
        log_step "BitWarden: Logging in..."
        BW_SESSION=$(bw login --raw)
        export BW_SESSION
    elif [[ "$status" == "locked" ]]; then
        log_step "BitWarden: Unlocking vault..."
        BW_SESSION=$(bw unlock --raw)
        export BW_SESSION
    else
        log_info "BitWarden: Session active"
    fi

    return 0
}

provider_list_items() {
    bw list items --search "OCI Terraform -" 2>/dev/null | jq -r '.[].name' 2>/dev/null || echo ""
}

provider_get_item() {
    local item_name="$1"
    bw get item "$item_name" 2>/dev/null
}

provider_get_field() {
    local item_json="$1"
    local field_name="$2"
    echo "$item_json" | jq -r ".fields[]? | select(.name == \"$field_name\") | .value // empty" 2>/dev/null
}

provider_get_item_id() {
    local item_json="$1"
    echo "$item_json" | jq -r '.id'
}

# NOTE: Attachments are no longer used. PEM keys are stored as text fields.
# This function is kept for backwards compatibility but is deprecated.
provider_get_attachment() {
    log_warn "Attachments are deprecated. PEM keys should be stored as text fields."
    return 1
}

provider_create_item() {
    local item_name="$1"
    local fields_json="$2"

    local item_json
    item_json=$(jq -n \
        --arg name "$item_name" \
        --argjson fields "$fields_json" \
        '{
            type: 2,
            secureNote: { type: 0 },
            name: $name,
            notes: "Terraform configuration for OCI Kubernetes cluster. Generated by tfvars-setup.",
            fields: $fields
        }')

    echo "$item_json" | bw encode | bw create item
}

provider_update_item() {
    local item_id="$1"
    local item_name="$2"
    local new_fields_json="$3"

    # Get existing item to preserve fields not in new_fields
    local existing_item
    existing_item=$(bw get item "$item_id" 2>/dev/null)

    # Merge fields: new fields override existing, but keep fields not in new
    local merged_fields
    merged_fields=$(echo "$existing_item" | jq --argjson new "$new_fields_json" '
        # Get existing fields as object keyed by name
        (.fields // []) as $existing |
        # Get new fields as object keyed by name
        ($new | map({(.name): .}) | add // {}) as $new_obj |
        # Get existing as object keyed by name
        ($existing | map({(.name): .}) | add // {}) as $existing_obj |
        # Merge: existing + new (new overrides)
        ($existing_obj + $new_obj) | to_entries | map(.value)
    ')

    local item_json
    item_json=$(echo "$existing_item" | jq \
        --argjson fields "$merged_fields" \
        '.fields = $fields | .notes = "Terraform configuration for OCI Kubernetes cluster. Updated by tfvars-setup."')

    echo "$item_json" | bw encode | bw edit item "$item_id"
}

# NOTE: Attachments are no longer used. PEM keys are stored as text fields.
provider_add_attachment() {
    log_warn "Attachments deprecated - PEM keys are now stored as text fields"
    return 0
}

provider_sync() {
    bw sync > /dev/null 2>&1
}

# ============================================================================
# BITWARDEN-SPECIFIC FIELD BUILDING
# ============================================================================

# Build fields JSON array for BitWarden
# BitWarden uses: { name: "field_name", value: "value", type: 0|1 }
# type: 0 = text, 1 = hidden
provider_build_fields_json() {
    local fields="[]"

    # Helper to add a field
    _add_bw_field() {
        local name="$1"
        local value="$2"
        local hidden="${3:-0}"  # 0 = text, 1 = hidden

        if [[ -n "$value" ]]; then
            fields=$(echo "$fields" | jq \
                --arg name "$name" \
                --arg value "$value" \
                --argjson type "$hidden" \
                '. + [{name: $name, value: $value, type: $type}]')
        fi
    }

    # OCI Authentication
    _add_bw_field "oci_tenancy_ocid" "${CONFIG_OCI_TENANCY_OCID:-}"
    _add_bw_field "oci_user_ocid" "${CONFIG_OCI_USER_OCID:-}"
    _add_bw_field "oci_fingerprint" "${CONFIG_OCI_FINGERPRINT:-}"
    _add_bw_field "oci_region" "${CONFIG_OCI_REGION:-}"
    _add_bw_field "oci_namespace" "${CONFIG_OCI_NAMESPACE:-}"
    _add_bw_field "oci_compartment_id" "${CONFIG_OCI_COMPARTMENT_ID:-}"

    # OCI Infrastructure
    _add_bw_field "oci_public_subnet_id" "${CONFIG_OCI_PUBLIC_SUBNET_ID:-}"
    _add_bw_field "oci_vault_id" "${CONFIG_OCI_VAULT_ID:-}"

    # Cluster Config
    _add_bw_field "domain" "${CONFIG_DOMAIN:-}"
    _add_bw_field "github_org" "${CONFIG_GITHUB_ORG:-}"
    _add_bw_field "github_repo" "${CONFIG_GITHUB_REPO:-}"
    _add_bw_field "github_email" "${CONFIG_GITHUB_EMAIL:-}"
    _add_bw_field "admin_username" "${CONFIG_ADMIN_USERNAME:-}"
    _add_bw_field "ssh_public_key" "${CONFIG_SSH_PUBLIC_KEY:-}"

    # GitHub FluxCD (secrets are hidden)
    _add_bw_field "gh_token" "${CONFIG_GH_TOKEN:-}" 1
    _add_bw_field "github_app_id" "${CONFIG_GITHUB_APP_ID:-}"
    _add_bw_field "github_app_installation_id" "${CONFIG_GITHUB_APP_INSTALLATION_ID:-}"

    # GitHub OAuth Dex
    _add_bw_field "github_dex_client_id" "${CONFIG_GITHUB_DEX_CLIENT_ID:-}"
    _add_bw_field "github_dex_client_secret" "${CONFIG_GITHUB_DEX_CLIENT_SECRET:-}" 1

    # GitHub OAuth Teleport
    _add_bw_field "teleport_github_org" "${CONFIG_TELEPORT_GITHUB_ORG:-}"
    _add_bw_field "teleport_github_client_id" "${CONFIG_TELEPORT_GITHUB_CLIENT_ID:-}"
    _add_bw_field "teleport_github_client_secret" "${CONFIG_TELEPORT_GITHUB_CLIENT_SECRET:-}" 1

    # Cloudflare
    _add_bw_field "cloudflare_api_token" "${CONFIG_CLOUDFLARE_API_TOKEN:-}" 1

    # Telegram
    _add_bw_field "telegram_bot_token" "${CONFIG_TELEGRAM_BOT_TOKEN:-}" 1
    _add_bw_field "telegram_chat_id" "${CONFIG_TELEGRAM_CHAT_ID:-}" 1

    # Kubernetes
    _add_bw_field "kubernetes_version" "${CONFIG_KUBERNETES_VERSION:-}"
    _add_bw_field "kubernetes_arm_node_pool_enabled" "${CONFIG_KUBERNETES_ARM_ENABLED:-}"
    _add_bw_field "kubernetes_arm_node_pool_size" "${CONFIG_KUBERNETES_ARM_SIZE:-}"
    _add_bw_field "kubernetes_x86_node_pool_enabled" "${CONFIG_KUBERNETES_X86_ENABLED:-}"
    _add_bw_field "kubernetes_x86_node_pool_size" "${CONFIG_KUBERNETES_X86_SIZE:-}"
    _add_bw_field "kubernetes_x86_ocpus" "${CONFIG_KUBERNETES_X86_OCPUS:-}"
    _add_bw_field "kubernetes_x86_memory_gb" "${CONFIG_KUBERNETES_X86_MEMORY:-}"
    _add_bw_field "kubernetes_x86_shape" "${CONFIG_KUBERNETES_X86_SHAPE:-}"

    # Apps Repository (optional)
    _add_bw_field "apps_enabled" "${CONFIG_APPS_ENABLED:-}"
    _add_bw_field "apps_github_org" "${CONFIG_APPS_GITHUB_ORG:-}"
    _add_bw_field "apps_github_repo" "${CONFIG_APPS_GITHUB_REPO:-}"

    # GitHub ARC
    _add_bw_field "github_arc_app_id" "${CONFIG_GITHUB_ARC_APP_ID:-}"
    _add_bw_field "github_arc_private_key" "${CONFIG_GITHUB_ARC_PRIVATE_KEY:-}" 1
    _add_bw_field "github_arc_shingonoide_installation_id" "${CONFIG_GITHUB_ARC_SHINGONOIDE_INSTALL_ID:-}"
    _add_bw_field "github_arc_dictmagic_installation_id" "${CONFIG_GITHUB_ARC_DICTMAGIC_INSTALL_ID:-}"

    # PEM Keys (stored as text fields instead of attachments)
    _add_bw_field "oci_private_key" "${CONFIG_OCI_PRIVATE_KEY:-}" 1
    _add_bw_field "github_app_pem" "${CONFIG_GITHUB_APP_PEM:-}" 1

    echo "$fields"
}
